### ISSUE TITLE
Add "Why / Motivation / Use Cases" section in README.md

### ISSUE THREAD

**Issue by dimisjim** [tfverch/tfvc#22]
From reading through it a bit, it seems that this tool provides functionality that's already part of what tools such as renovate and dependabot already provide.

What extra functionality does this project offer?
Am I missing something?

**Comment by ryan-jan** [comment]
@dimisjim not quite sure how this is an issue lol. It is not solving a problem, it's simply providing a different way to manage these dependencies. I need a simple tool to report on the version status of a terraform codebase, not to fully handle all updates etc manually. I use this day to day and decided to share it with the community in case others find it useful. If you do not then feel free to NOT use it :-)

**Comment by dimisjim** [comment]
It is an issue, coz there is no clear way to see how this utility helps to solve versioning problems.
Maybe a "Why / Motivation / Use Cases" section in the main README could help in that regard + defining these problems with examples. What do you think?

I meant no offense, and I am sorry that you took it this way. I am simply curious on its utility and use cases.

**Comment by ryan-jan** [comment]
@dimisjim  OK, apologies I maybe jumped the gun there! I do get the point that the readme/docs need to be a bit more informative about what the motivation was for this project. It is still early days and there are issues and features I need to address. I'll make a note to improve the readme at some point. Cheers.

**Comment by dimisjim** [comment]
Would it then make sense to keep this issue open?
